schemaspy.t=mysql
schemaspy.host=localhost
schemaspy.port=3306
schemaspy.db=icc_munich
schemaspy.u=root
schemaspy.p=
schemaspy.o=docs/database
schemaspy.dp=tools/mysql-connector-j-8.0.33.jar
schemaspy.s=icc_munich
# Disable diagram generation to avoid Graphviz dependency errors
schemaspy.vizjs=true