<?php

namespace App\Models;

use App\Enums\Report\ReportType;
use App\Enums\Report\ReportPeriodType;
use App\Traits\ClearsCache;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

/**
 * @property int $id
 * @property string $uuid
 * @property int|null $department_id
 * @property string $name
 * @property string|null $description
 * @property ReportType $type
 * @property ReportPeriodType $period_type
 * @property array<array-key, mixed>|null $sections_config
 * @property array<array-key, mixed>|null $default_approvers
 * @property bool $is_active
 * @property bool $auto_generate
 * @property int|null $auto_generate_day
 * @property array<array-key, mixed>|null $metadata
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \Spatie\Activitylog\Models\Activity> $activities
 * @property-read int|null $activities_count
 * @property-read \App\Models\Department|null $department
 * @property-read string $period_type_label
 * @property-read string $type_label
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \App\Models\ReportReminder> $reminders
 * @property-read int|null $reminders_count
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \App\Models\DepartmentReport> $reports
 * @property-read int|null $reports_count
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate active()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate autoGenerate()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate byType(\App\Enums\Report\ReportType $type)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate forDepartment(int $id)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereAutoGenerate($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereAutoGenerateDay($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereDefaultApprovers($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereDepartmentId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereIsActive($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereMetadata($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate wherePeriodType($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereSectionsConfig($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate whereUuid($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate withTrashed(bool $withTrashed = true)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ReportTemplate withoutTrashed()
 * @mixin \Eloquent
 */
class ReportTemplate extends Model
{
    use HasFactory, SoftDeletes, LogsActivity, ClearsCache;

    protected $fillable = [
        'uuid',
        'department_id',
        'name',
        'description',
        'type',
        'period_type',
        'sections_config',
        'default_approvers',
        'is_active',
        'auto_generate',
        'auto_generate_day',
        'metadata',
    ];

    protected $casts = [
        'type' => ReportType::class,
        'period_type' => ReportPeriodType::class,
        'sections_config' => 'array',
        'default_approvers' => 'array',
        'is_active' => 'boolean',
        'auto_generate' => 'boolean',
        'metadata' => 'array',
    ];

    protected $appends = [
        'type_label',
        'period_type_label',
    ];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logFillable()
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs();
    }

    protected static function boot(): void
    {
        parent::boot();
        static::creating(fn($m) => $m->uuid ??= (string) Str::uuid());
    }

    public function getRouteKeyName(): string
    {
        return 'uuid';
    }

    // Relations
    public function department(): BelongsTo
    {
        return $this->belongsTo(Department::class);
    }

    public function reports(): HasMany
    {
        return $this->hasMany(DepartmentReport::class, 'template_id');
    }

    public function reminders(): HasMany
    {
        return $this->hasMany(ReportReminder::class, 'template_id');
    }

    // Scopes
    public function scopeActive($q)
    {
        return $q->where('is_active', true);
    }

    public function scopeForDepartment($q, int $id)
    {
        return $q->where('department_id', $id);
    }

    public function scopeAutoGenerate($q)
    {
        return $q->where('auto_generate', true);
    }

    public function scopeByType($q, ReportType $type)
    {
        return $q->where('type', $type->value);
    }

    // Accessors
    public function getTypeLabelAttribute(): string
    {
        return $this->type->label();
    }

    public function getPeriodTypeLabelAttribute(): string
    {
        return $this->period_type->label();
    }

    // Methods
    public function getSectionsConfig(): array
    {
        return $this->sections_config ?? $this->type->defaultSections();
    }

    public function getDefaultApprovers(): array
    {
        return $this->default_approvers ?? [];
    }
}
